import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import Image from 'next/image'
import logo from '../public/ttjs.png'
import logom from '../public/ttjm.png'
import logol from '../public/ttjl.png'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href='#'>
              <img className='logo mobilelogo'
              src='ttjm.png'
              alt="Thrill Top Journeys Logo"
            />
          </Link>
          <input type="checkbox" id="nav-toggle" className='nav-toggle'/>
          <label htmlFor='nav-toggle' className='nav-toggle-label'>
            <div></div><div></div>
          </label>

        <nav className='globalnav'>
            <ul>
              <li><Link href='#'>
                <img className='logo bigscreenlogo'
                src='ttjm.png'
                alt="Thrill Top Journeys Logo"
              />
              </Link></li>
              <li><Link href='#'>Group Tours</Link></li>
              <li><Link href='#'>Inspirations</Link></li>
              <li><Link href='#'>Solo Travel</Link></li>
              <li><Link href='#'>Offers</Link></li>
              <li><Link href='#'>Contact Us</Link></li>
              <li><Link href='#'>
                <img src='heart-fat.svg'/>  
              </Link></li>
            </ul>
        </nav>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
